
-- Top1
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P0',N'C01',N'Chaos Tee - Beige',360,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P1',N'C01',N'High Planet Tee - Green',360,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P2',N'C01',N'Ludo Tee - Brown',360,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P3',N'C01',N'Ludo Tee - Black',360,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P4',N'C01',N'Highclub 24 Tee - Brown',360,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P5',N'C01',N'Sticker Tee - Red',350,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P6',N'C01',N'Tiger Tee - Red',350,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P7',N'C01',N'Tiger Tee - White',350,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P8',N'C01',N'Tiger Tee - Black',350,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P9',N'C01',N'F1 Highway Tee - Black',350,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P10',N'C01',N'Freedom Tee - Brown',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P11',N'C01',N'Freedom Tee - Beige',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P12',N'C01',N'Graffiti Tee - White',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P13',N'C01',N'Graffiti Tee - Black',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P14',N'C01',N'The Zoo Tee - Black',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P15',N'C01',N'The Zoo Tee - White',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P16',N'C01',N'Monster Tee - Black',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P17',N'C01',N'Monster Tee - White',340,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P18',N'C01',N'SprayPaint Tee - Brown',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P19',N'C01',N'SprayPaint Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P20',N'C01',N'Tarot Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P21',N'C01',N'Tarot Tee - Beige',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P22',N'C01',N'Kindness Tee - Beige',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P23',N'C01',N'Kindness Tee - White',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P24',N'C01',N'Magic Chrome Tee - White',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P25',N'C01',N'Magic Chrome Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P26',N'C01',N'Magic Chrome Tee - Blue Steel',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P27',N'C01',N'Magic Chrome Tee - Grey',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P28',N'C01',N'Eat Me Washed Tee - Grey',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P29',N'C01',N'Eat Me Tee - Cream/White',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P30',N'C01',N'High Universe Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P31',N'C01',N'High Universe Tee - White',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P32',N'C01',N'Racing Labels Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P33',N'C01',N'Racing Labels Tee - White',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P34',N'C01',N'Ghost Gate Tee - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P35',N'C01',N'HighClub Badge Tee - Brown',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P36',N'C01',N'HighClub Badge Tee - Red',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P37',N'C01',N'HighClub Badge Tee - Green',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P38',N'C01',N'HighClub Badge Tee - Beige',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P39',N'C01',N'HighClub Badge Tee - Black',320,10,5,15);

--Top2
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P40',N'C01',N'HighClub Badge Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P41',N'C01',N'Joyful Tee - Black',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P42',N'C01',N'Joyful Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P43',N'C01',N'Highlife Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P44',N'C01',N'Highlife Tee - Beige',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P45',N'C01',N'Dinosaur Tee - Black',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P46',N'C01',N'Dinosaur Tee - Beige',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P47',N'C01',N'Flash Card Tee - Beige',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P48',N'C01',N'Flash Card Tee - Pink',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P49',N'C01',N'The Painting Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P50',N'C01',N'Happy Tee - Grey',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P51',N'C01',N'Happy Tee - Brown',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P52',N'C01',N'Happy Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P53',N'C01',N'Happy Tee - Black',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P54',N'C01',N'Basic Tee - Black',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P55',N'C01',N'Call My Papa Tee - White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P56',N'C01',N'Call My Mama Tee - Black',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P57',N'C01',N'Basic Tee - Navy',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P58',N'C01',N'Basic Tee - Cream/White',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P59',N'C01',N'Basic Washed Tee - Grey',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P60',N'C01',N'Basic V2 Tee - White/Red',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P61',N'C01',N'Basic V2 Tee - Beige/Black',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P62',N'C01',N'Basic V2 Tee - Black/Pink',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P63',N'C01',N'Basic V2 Tee - Pink/White',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P64',N'C01',N'Chubby Tee - Black',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P65',N'C01',N'Chubby Tee - White',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P66',N'C01',N'Unique Tee - Beige/White',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P67',N'C01',N'Pocket Basic Tee - Dark Brown',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P68',N'C01',N'Pocket Basic Tee - Brown',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P69',N'C01',N'Pocket Basic Tee - Red',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P70',N'C01',N'Pocket Basic Tee - Black',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P71',N'C01',N'Pocket Basic Tee - Cream/White',280,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P72',N'C01',N'Overflow Tee - White/Black',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P73',N'C01',N'Overflow Tee - White/Pink',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P74',N'C01',N'Overflow Tee - Black/White',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P75',N'C01',N'Overflow Tee - Black/Yellow',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P76',N'C01',N'Volcano Tee - White',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P77',N'C01',N'Volcano Tee - Black',250,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P78',N'C01',N'Khu Tập Thể Tee - Black',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P79',N'C01',N'Overflow Longsleeve - Pink',230,10,5,15);

--Top 3
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P80',N'C01',N'Cookie Tee - White',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P81',N'C01',N'Cookie Tee - Black',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P82',N'C01',N'Sushi Tee - White',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P83',N'C01',N'Sushi Tee - Black',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P84',N'C01',N'Rio Tee - White',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P85',N'C01',N'Rio Tee - Black',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P86',N'C01',N'Khu Tập Thể Tee - White',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P87',N'C01',N'Butterfly Tee - Black',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P88',N'C01',N'Butterfly Tee - White',230,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P89',N'C01',N'Basic Tee - Brown/White',190,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P90',N'C01',N'Basic Tee - Pink/White',190,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P91',N'C01',N'Basic Tee - Red/White',190,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P92',N'C01',N'Basic Tee - Green/White',190,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P93',N'C01',N'Basic Tee - White/Black',190,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P94',N'C01',N'Basic Tee - Black/White',190,10,5,15);

--Bottoms
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P95',N'C02',N'Basic Short - Black',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P96',N'C02',N'Basic Short - Brown',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P97',N'C02',N'Basic Short - Cream',330,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P98',N'C02',N'Cargo Pant - Black',450,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P99',N'C02',N'Corduroy Pant - Black',420,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P100',N'C02',N'Corduroy Pant - Brown',420,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P101',N'C02',N'Corduroy Pant - Grey',420,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P102',N'C02',N'Logo Wordmark Pants',390,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P103',N'C02',N'Logo Wordmark Shorts',320,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P104',N'C02',N'Short Signature',200,10,5,15);

--Outerwears
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P105',N'C03',N'Athlete Track Jacket - White',595,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P106',N'C03',N'Highclub 24 Sweater - Brown',450,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P107',N'C03',N'Highclub Badge Varsity - Black',550,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P108',N'C03',N'Highclub Badge Varsity - Blue',550,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P109',N'C03',N'Hoodie Basic - Black/Neon Pink',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P110',N'C03',N'Hoodie Basic - Red/White',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P111',N'C03',N'Hoodie Basic - White/Red',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P112',N'C03',N'Hoodie Basic Pastel - Black/Pink',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P113',N'C03',N'Hoodie Basic Pastel - Blue/White',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P114',N'C03',N'Hoodie Basic Pastel - Pink/White',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P115',N'C03',N'Logo Pattern Cardigan - Beige',550,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P116',N'C03',N'Logo Pattern Cardigan - Black',550,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P117',N'C03',N'Logo Wordmark Jacket - Black',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P118',N'C03',N'Logo Wordmark Jacket - White',480,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P119',N'C03',N'Racing Overprint - Jacket',550,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P120',N'C03',N'Sweater Joyful - White',420,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P121',N'C03',N'The Painting Sweater - White',420,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P122',N'C03',N'UFO Jacket - Black',595,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P123',N'C03',N'Venomous Jacket - Black',580,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P124',N'C03',N'Worldwide Bomber',600,10,5,15);

--Accessories
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P125',N'C04',N'Cap Crazy - Black',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P126',N'C04',N'Cap Crazy - Gray',300,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P127',N'C04',N'Gump Backpack - Blue',390,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P128',N'C04',N'Gump Backpack - Pink',390,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P129',N'C04',N'Highble Sock - Black',650,10,5,15);
INSERT INTO Product(idProduct,idCollection,nameProduct,price,sizeXL,sizeM,sizeL) VALUES (N'P130',N'C04',N'Highble Sock - Brown',650,10,5,15);
